### ISSUE TITLE
fmriprep-group-report doesn't support older fmriprep versions (< 21.0.0), yet

### ISSUE THREAD

**Issue by JessyD** [nimh-comppsych/fmriprep-group-report#1]
The code for fmriprep-group-report was tested and created using the outputs from fmriprep 21.0.0 in mind. Compared to the older versions, fmriprep 21.0.0 now consolidates the figures output at the subject level. So as it is, the code for fmripep-group-report will run, but the consolidated files will not display the subject's images.

**Comment by YohanWards** [comment]
Hi, I'd love for this to be able to work on older versions too if you can make that work. I'm using fMRIprep v20.2.3 on a large N study with several groups so this tool would be super useful for us.

**Comment by JessyD** [comment]
PR https://github.com/nimh-comppsych/fmriprep-group-report/pull/4 adapts the code so that fmriprep-group-report can be used for other versions than fmriprep 21.0.0.
The code was tested using fmriprep 20.0.6 and 20.2.3.
